[nfs]
<172.31.44.252> ansible_ssh_user='ubuntu'

[webservers]
<172.31.32.240> ansible_ssh_user='ubuntu'
<172.31.32.192> ansible_ssh_user='ubuntu'

[db]
<172.31.35.129> ansible_ssh_user='ubuntu' 

[lb]
<172.31.44.2> ansible_ssh_user='ubuntu'
