[nfs]
<172.31.40.63> ansible_ssh_user='ec2-user'

[webservers]
<172.31.35.194> ansible_ssh_user='ec2-user'
<172.31.35.236> ansible_ssh_user='ec2-user'

[db]
<172.31.40.51> ansible_ssh_user='ec2-user' 

[lb]
<172.31.32.205> ansible_ssh_user='ubuntu'