---
#- hosts: db
#  name: database assignment
#  tasks:
#    - import_playbook: ../static-assignments/database.yml
- name: nginx assignment
  hosts: nginx
  tasks:
    - include: ../static-assignments/nginx.yml
# - hosts: artifactory
# - name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonar
# - name: sonar assignment
#  ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml